name: create-draft-release
on:
  workflow_dispatch:
jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: install gh cli
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C998B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
          
      - name: create draft release
        run: |
          GH_TOKEN=${{ secrets.GH_TOKEN }}
          REPO=${{ github.repository }}
          LATEST_TAG=$(gh release list --repo $REPO --limit 1 --json tagName -q '.[0].tagName')
          IFS='.' read -ra ADDR <<< "$LATEST_TAG"
          NEW_PATCH=$(( ${ADDR[2]} + 1 ))
          NEW_TAG="${ADDR[0]}.${ADDR[1]}.$NEW_PATCH
          echo "Creating new draft release $NEW_TAG"
          gh release create $NEW_TAG --repo $REPO --title $NEW_TAG --notes "Draft release --draft
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
